# Generated by Django 3.2 on 2022-01-13 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_izdavanja_racuna', models.DateTimeField(default=django.utils.timezone.now)),
                ('ukupna_cena', models.FloatField()),
                ('racun_izdao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StavkeRacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_stavke', models.CharField(max_length=200)),
                ('opis_stavke', models.TextField()),
                ('cena_stavke', models.FloatField()),
                ('radni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.racun')),
            ],
        ),
        migrations.CreateModel(
            name='RadniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_podnosenja_radnog_naloga', models.DateTimeField(default=django.utils.timezone.now)),
                ('radni_nalog_kod', models.CharField(max_length=20)),
                ('ime_prezime_klijenta', models.CharField(max_length=200)),
                ('opis_kvara', models.TextField()),
                ('marka_automobila', models.CharField(choices=[('BMW', 'BMW'), ('Audi', 'Audi'), ('Citroen', 'Citroen'), ('Fiat', 'Fiat'), ('Renault', 'Renault')], max_length=30)),
                ('model_automobila', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('UT', 'Radni nalog u toku'), ('OK', 'Radni nalog je zavrsen uspesno'), ('NO', 'Radni nalog je prekinut')], max_length=5)),
                ('opis_servisera', models.TextField(blank=True, default='Servis nije stavio nikakav opis')),
                ('radni_nalog_podneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='racun',
            name='radni_nalog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servis.radninalog'),
        ),
        migrations.CreateModel(
            name='ProgresRadnogNaloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_belezenja_progresa', models.DateTimeField(default=django.utils.timezone.now)),
                ('opis_progresa', models.TextField()),
                ('radni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.radninalog')),
                ('zabelezio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IzdatnicaMagacin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_podnosenje_izdatnice', models.DateTimeField(default=django.utils.timezone.now)),
                ('izdatnicu_podneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.radninalog')),
            ],
        ),
        migrations.CreateModel(
            name='DeloviIzdatnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrebni_deo', models.CharField(max_length=200)),
                ('komada', models.PositiveIntegerField(default=1)),
                ('izdatnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.izdatnicamagacin')),
            ],
        ),
    ]
