# Generated by Django 3.2 on 2022-01-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0003_izdatnicamagacin_ispenjeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racun',
            name='ukupna_cena',
            field=models.FloatField(default=0),
        ),
    ]
