# Generated by Django 3.2 on 2022-01-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0004_alter_racun_ukupna_cena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stavkeracuna',
            old_name='radni_nalog',
            new_name='racun',
        ),
    ]
