# Generated by Django 3.2 on 2022-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0006_radninalog_registracija'),
    ]

    operations = [
        migrations.AddField(
            model_name='izdatnicamagacin',
            name='odobren',
            field=models.BooleanField(default=False),
        ),
    ]
