# Generated by Django 3.2 on 2022-01-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0008_auto_20220114_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='izdatnicamagacin',
            name='komada',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='izdatnicamagacin',
            name='potrebni_deo',
            field=models.CharField(default='Temp izmena', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeloviIzdatnica',
        ),
    ]
