# Generated by Django 3.2 on 2022-01-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0009_auto_20220114_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izdatnicamagacin',
            name='ispenjeno',
        ),
        migrations.RemoveField(
            model_name='izdatnicamagacin',
            name='odbio_magacin',
        ),
        migrations.RemoveField(
            model_name='izdatnicamagacin',
            name='odobren_sef',
        ),
        migrations.AddField(
            model_name='izdatnicamagacin',
            name='status',
            field=models.CharField(choices=[('OS', 'Ceka se odobrenje sefa'), ('SO', 'Sef je odbio porucivanje'), ('SP', 'Sef porucio delove iz magacina'), ('MO', 'Magacin odbio porudzbinu'), ('OK', 'Magacin dostavio porudzbinu')], default='OS', max_length=10),
        ),
    ]
