# Generated by Django 3.2 on 2022-01-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0010_auto_20220114_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radninalog',
            name='opis_servisera',
        ),
    ]
