# Generated by Django 3.2 on 2022-01-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0012_radninalog_kontakt_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='registracija',
            field=models.CharField(blank=True, default='---', max_length=15),
        ),
    ]
