# Generated by Django 3.2 on 2022-01-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0015_alter_radninalog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radninalog',
            name='marka_automobila',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Audi', 'Audi'), ('Citroen', 'Citroen'), ('Fiat', 'Fiat'), ('Renault', 'Renault'), ('Alfa Romeo', 'Alfa Romeo'), ('Mercedes', 'Mercedes'), ('Toyota', 'Toyota'), ('KIA', 'KIA'), ('Ford', 'Ford'), ('Skoda', 'Skoda')], max_length=30),
        ),
    ]
