# Generated by Django 3.2 on 2022-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='pozicija',
            field=models.CharField(choices=[('SS', 'Sef servisa'), ('S', 'Servise'), ('M', 'Magacioner')], max_length=3),
        ),
    ]
